language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '7'
before_script:
  - npm prune
script:
  - npm test -- --coverage --collectCoverageFrom=src/components/**/*.js
after_success:
  - npm run report-coverage
  - npm run semantic-release
  - npm run build-storybook
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: storybook-static
  github_token: "$GH_TOKEN" # Set in travis-ci.org dashboard
  on:
    branch: master
